AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Max: 110

Style/ClassAndModuleChildren:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i':    '()'
    '%w':    '()'