name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.3
        bundle install
    - name: Rubocop
      run: bundle exec rake rubocop
    - name: Spec
      run: bundle exec rake spec
